// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijmxxysgzkfedumfpyso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbXh4eXNnemtmZWR1bWZweXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NzA1MTksImV4cCI6MjA4NjU0NjUxOX0.fchMTeOCt2Vhx9_YYstX4N2HzAvzzhIyWprR0MqW1HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});